[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
    "python3.11 -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "python3.11 bot.py"
